-- Create synthetic data by sampling and modifying original nedis2017 data
-- This creates realistic synthetic data with slight variations

-- First, let's sample 100,000 records and add some realistic noise
CREATE TABLE nedis2017_synthetic AS
SELECT
    -- Keep identifiers similar but modified
    'SYNTH_' || CAST((random() * 1000000) AS INTEGER) AS index_key,
    emorg_cd,
    vst_dt,
    vst_tm,
    'PAT_' || CAST((random() * 1000000) AS INTEGER) AS pat_reg_no,
    flag_stue,
    pat_brdt,
    pat_age,
    pat_age_gr,
    pat_sex,
    pat_sex_cd,
    pat_sarea,
    pat_do_cd,
    pat_gu_cd,
    insp_tp,
    mcorg_cd,
    ocur_dt,
    ocur_tm,
    vst_sck,
    vst_ity,
    vst_meth,
    vst_bdht,
    -- Add realistic noise to vital signs (±5% variation)
    CASE WHEN vst_sbp > 0 THEN CAST(vst_sbp * (0.95 + random() * 0.1) AS INTEGER) ELSE vst_sbp END as vst_sbp,
    CASE WHEN vst_dbp > 0 THEN CAST(vst_dbp * (0.95 + random() * 0.1) AS INTEGER) ELSE vst_dbp END as vst_dbp,
    CASE WHEN vst_per_pu > 0 THEN CAST(vst_per_pu * (0.95 + random() * 0.1) AS INTEGER) ELSE vst_per_pu END as vst_per_pu,
    CASE WHEN vst_per_br > 0 THEN CAST(vst_per_br * (0.95 + random() * 0.1) AS INTEGER) ELSE vst_per_br END as vst_per_br,
    CASE WHEN vst_oxy > 0 THEN CAST(vst_oxy * (0.98 + random() * 0.04) AS INTEGER) ELSE vst_oxy END as vst_oxy,
    vst_bt,
    vst_wt,
    vst_react,
    vst_rute,
    vst_dmg,
    ktas_fstu,
    ktas_rcrp,
    ktas_brth,
    ktas_nrpr,
    ktas_nt,
    ktas_fid,
    main_sick,
    main_damg,
    scond_sick,
    scond_damg,
    emtrt_rust,
    msypt,
    msypt1,
    msypt2,
    msypt3,
    msypt4,
    msypt5,
    msypt6,
    msypt7,
    msypt8,
    msypt9,
    msypt10,
    msypt11,
    msypt12,
    msypt13,
    msypt14,
    msypt15,
    msypt16,
    msypt17,
    msypt18,
    msypt19,
    msypt20,
    msypt21,
    msypt22,
    msypt23,
    main_trt_p,
    main_trt1,
    main_trt2,
    main_trt3,
    main_trt4,
    main_trt5,
    emtrt_surt,
    emtrt_ourt,
    taip,
    shog,
    care_bt,
    care_by,
    care_fair,
    care_gd,
    care_ht,
    care_sair,
    care_vt,
    care_nowea,
    care_noip,
    care_non,
    trd_org_tp,
    trd_org_cd,
    trs_org_tp,
    trs_org_cd,
    ca,
    'SYNTH_NAME_' || CAST((random() * 10000) AS INTEGER) AS pat_nm,  -- Anonymize patient names
    key,
    base,
    hospname,
    gubun,
    adr,
    etc,
    otpat_sn,
    otpat_grd,
    vr_dt,
    emorg,
    emsypt_yn,
    ktas01
FROM nedis2017
WHERE random() < 0.011  -- Sample approximately 100,000 records (1.1% of 9M)
ORDER BY random();