#!/usr/bin/env python3
"""
캐시된 패턴(pkl/json)을 최적화하여 단일 JSON으로 내보내는 스크립트.
HTML 생성기에 임베드할 용도로, count 제거/확률 필터링/소수점 반올림을 수행합니다.

Note: pickle은 이 프로젝트의 PatternAnalyzer가 생성한 신뢰할 수 있는 캐시 파일만 로드합니다.
"""

import json
import pickle  # nosec B403 - loading trusted cache files generated by our own PatternAnalyzer
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = PROJECT_ROOT / "cache" / "patterns"
TIME_CACHE_DIR = PROJECT_ROOT / "cache" / "time_patterns"
OUTPUT_PATH = PROJECT_ROOT / "outputs" / "html_generator" / "patterns.json"

PROB_THRESHOLD = 0.001  # hospital_allocation, chief_complaint에서 필터링 기준
DECIMAL_PLACES = 5


def get_latest_hash() -> str:
    """cache_metadata.json에서 가장 최신 data_hash를 찾는다."""
    meta_path = CACHE_DIR / "cache_metadata.json"
    with open(meta_path) as f:
        meta = json.load(f)

    entries = meta["cache_entries"]
    hash_dates = {}
    for entry in entries.values():
        h = entry["data_hash"]
        ts = entry.get("created_at", "")
        if h not in hash_dates or ts > hash_dates[h]:
            hash_dates[h] = ts

    latest_hash = max(hash_dates, key=hash_dates.get)
    print(f"[INFO] Latest data hash: {latest_hash}")
    return latest_hash


def load_pkl(pattern_type: str, data_hash: str) -> dict:
    path = CACHE_DIR / f"{pattern_type}_{data_hash}.pkl"
    with open(path, "rb") as f:
        return pickle.load(f)  # nosec B301 - trusted cache file


def round_val(v, places=DECIMAL_PLACES):
    return round(v, places)


def filter_and_renormalize(prob_dict: dict, threshold: float) -> dict:
    """확률이 threshold 이상인 항목만 남기고 재정규화."""
    filtered = {k: v for k, v in prob_dict.items() if v >= threshold}
    if not filtered:
        max_key = max(prob_dict, key=prob_dict.get)
        filtered = {max_key: prob_dict[max_key]}
    total = sum(filtered.values())
    return {k: round_val(v / total) for k, v in filtered.items()}


def extract_demographic_patterns(data_hash: str) -> dict:
    raw = load_pkl("demographic_patterns", data_hash)
    result = {}
    for key, val in raw["patterns"].items():
        result[key] = round_val(val["probability"])
    return result


def extract_regional_patterns(data_hash: str) -> dict:
    raw = load_pkl("regional_patterns", data_hash)
    result = {}
    for key, val in raw["patterns"].items():
        result[key] = {
            "total_visits": val["total_visits"],
            "ktas1_rate": round_val(val["ktas1_rate"]),
            "urgent_rate": round_val(val["urgent_rate"]),
            "unique_hospitals": val["unique_hospitals"],
            "male_ratio": round_val(val["male_ratio"]),
        }
    return result


def build_hospital_code_map(data_hash: str) -> dict:
    """실제 병원코드를 수집하여 결정적 익명 매핑(H0001, H0002, ...)을 생성."""
    raw = load_pkl("hospital_allocation", data_hash)
    all_codes = set()
    for val in raw["patterns"].values():
        hospitals = val.get("hospitals", {})
        all_codes.update(hospitals.keys())
    if "hierarchical_fallback" in raw:
        for val in raw["hierarchical_fallback"].values():
            hospitals = val.get("hospitals", {})
            all_codes.update(hospitals.keys())
    sorted_codes = sorted(all_codes)
    code_map = {code: f"H{i + 1:04d}" for i, code in enumerate(sorted_codes)}
    print(f"  Hospital code anonymization: {len(code_map)} codes mapped (H0001 ~ H{len(code_map):04d})")
    return code_map


def extract_hospital_allocation(data_hash: str, code_map: dict) -> dict:
    raw = load_pkl("hospital_allocation", data_hash)
    result = {"patterns": {}, "hierarchical_fallback": {}}

    for region, val in raw["patterns"].items():
        hospitals = val.get("hospitals", {})
        prob_map = {h: info["probability"] for h, info in hospitals.items()}
        filtered = filter_and_renormalize(prob_map, PROB_THRESHOLD)
        result["patterns"][region] = {code_map.get(k, k): v for k, v in filtered.items()}

    if "hierarchical_fallback" in raw:
        for region, val in raw["hierarchical_fallback"].items():
            hospitals = val.get("hospitals", {})
            prob_map = {h: info["probability"] for h, info in hospitals.items()}
            filtered = filter_and_renormalize(prob_map, PROB_THRESHOLD)
            result["hierarchical_fallback"][region] = {code_map.get(k, k): v for k, v in filtered.items()}

    return result


def extract_ktas_distributions(data_hash: str) -> dict:
    raw = load_pkl("ktas_distributions", data_hash)
    result = {}

    for level_key in ["detailed_patterns", "major_patterns", "national_patterns"]:
        level_data = raw.get(level_key, {})
        result[level_key] = {}
        for key, val in level_data.items():
            if isinstance(val, dict):
                result[level_key][key] = {
                    k: round_val(v["probability"]) if isinstance(v, dict) and "probability" in v else v
                    for k, v in val.items()
                }

    if "overall_pattern" in raw:
        overall = raw["overall_pattern"]
        result["overall_pattern"] = {
            k: round_val(v["probability"]) if isinstance(v, dict) and "probability" in v else v
            for k, v in overall.items()
        }

    return result


def extract_simple_conditional(data_hash: str, pattern_type: str, apply_filter: bool = False) -> dict:
    """chief_complaint, department, treatment_result, visit_method 등의 패턴 추출."""
    raw = load_pkl(pattern_type, data_hash)
    result = {}
    for key, val in raw["patterns"].items():
        if isinstance(val, dict):
            prob_map = {}
            for code, info in val.items():
                if isinstance(info, dict) and "probability" in info:
                    prob_map[code] = info["probability"]
                elif isinstance(info, (int, float)):
                    prob_map[code] = info
            if apply_filter:
                prob_map = filter_and_renormalize(prob_map, PROB_THRESHOLD)
            else:
                prob_map = {k: round_val(v) for k, v in prob_map.items()}
            result[key] = prob_map
    return result


def extract_temporal_patterns(data_hash: str) -> dict:
    raw = load_pkl("temporal_patterns", data_hash)
    result = {}
    for period in ["monthly_pattern", "weekday_pattern", "hourly_pattern"]:
        if period in raw:
            result[period] = {
                str(k): round_val(v["probability"])
                for k, v in raw[period].items()
            }
    return result


def extract_conditional_temporal(data_hash: str) -> dict:
    """조건부 시간 패턴 추출. 8가지 조건부 분포."""
    path = CACHE_DIR / f"temporal_conditional_patterns_{data_hash}.pkl"
    if not path.exists():
        print(f"[WARN] Conditional temporal patterns not found: {path}")
        return {}
    with open(path, "rb") as f:
        raw = pickle.load(f)  # nosec B301 - trusted cache file

    patterns = raw.get("patterns", {})
    result = {}
    for cond_type, cond_data in patterns.items():
        result[cond_type] = {}
        for key, val in cond_data.items():
            if isinstance(val, dict):
                inner = val.get("patterns", val)
                result[cond_type][str(key)] = {
                    str(h): round_val(v["probability"]) if isinstance(v, dict) and "probability" in v else round_val(v)
                    for h, v in inner.items()
                }
    return result


def extract_time_gap_patterns() -> dict:
    """time_gap_patterns.json에서 lognorm 파라미터만 추출."""
    path = TIME_CACHE_DIR / "time_gap_patterns.json"
    with open(path) as f:
        raw = json.load(f)

    result = {}
    for key, gaps in raw.items():
        result[key] = {}
        for gap_name, params in gaps.items():
            result[key][gap_name] = {
                "shape": round_val(params.get("shape", 0)),
                "loc": round_val(params.get("loc", 0)),
                "scale": round_val(params.get("scale", 0)),
            }
    return result


def extract_comprehensive_time_patterns() -> dict:
    """comprehensive_time_patterns.json에서 hierarchical lognorm 파라미터 추출."""
    path = TIME_CACHE_DIR / "comprehensive_time_patterns.json"
    with open(path) as f:
        raw = json.load(f)

    hierarchical = raw.get("hierarchical", {})
    result = {}
    for level_name, level_data in hierarchical.items():
        result[level_name] = {}
        for key, gaps in level_data.items():
            result[level_name][key] = {}
            for gap_name, params in gaps.items():
                if isinstance(params, dict):
                    result[level_name][key][gap_name] = {
                        "shape": round_val(params.get("shape", 0)),
                        "loc": round_val(params.get("loc", 0)),
                        "scale": round_val(params.get("scale", 0)),
                    }
    return result


def main():
    data_hash = get_latest_hash()

    print("[1/10] Extracting demographic_patterns...")
    demographic = extract_demographic_patterns(data_hash)

    print("[2/10] Extracting regional_patterns...")
    regional = extract_regional_patterns(data_hash)

    print("[3/10] Extracting hospital_allocation (with anonymization)...")
    code_map = build_hospital_code_map(data_hash)
    hospital = extract_hospital_allocation(data_hash, code_map)

    print("[4/10] Extracting ktas_distributions...")
    ktas = extract_ktas_distributions(data_hash)

    print("[5/10] Extracting chief_complaint_patterns...")
    chief_complaint = extract_simple_conditional(data_hash, "chief_complaint_patterns", apply_filter=True)

    print("[6/10] Extracting department_patterns...")
    department = extract_simple_conditional(data_hash, "department_patterns")

    print("[7/10] Extracting treatment_result_patterns...")
    treatment_result = extract_simple_conditional(data_hash, "treatment_result_patterns")

    print("[8/10] Extracting visit_method_patterns...")
    visit_method = extract_simple_conditional(data_hash, "visit_method_patterns")

    print("[9/10] Extracting temporal_patterns...")
    temporal = extract_temporal_patterns(data_hash)
    conditional_temporal = extract_conditional_temporal(data_hash)

    print("[10/10] Extracting time gap patterns...")
    time_gaps = extract_time_gap_patterns()
    comprehensive_time = extract_comprehensive_time_patterns()

    output = {
        "demographic_patterns": demographic,
        "regional_patterns": regional,
        "hospital_allocation": hospital,
        "ktas_distributions": ktas,
        "chief_complaint_patterns": chief_complaint,
        "department_patterns": department,
        "treatment_result_patterns": treatment_result,
        "visit_method_patterns": visit_method,
        "temporal_patterns": temporal,
        "temporal_conditional_patterns": conditional_temporal,
        "comprehensive_time_patterns": comprehensive_time,
        "time_gap_patterns": time_gaps,
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(output, f, separators=(",", ":"))

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"\n[DONE] Output: {OUTPUT_PATH}")
    print(f"       Size: {size_kb:.1f} KB")

    for key, val in output.items():
        section_size = len(json.dumps(val, separators=(",", ":"))) / 1024
        print(f"  {key}: {section_size:.1f} KB")


if __name__ == "__main__":
    main()
